name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "0 0 * * *"
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  security-events: write
  # [Mandatory If using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  # id-token: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repository scanning will be triggered on the main branch.
        branch: ["main"]
    steps:
      - uses: jfrog/frogbot@v2.29.1
        env:
          # [Mandatory]
          JF_DEBUG: "true"
          JF_MIN_SEVERITY: "Low"
          JF_INCLUDE_ALL_VULNERABILITIES: "true"
          JF_DEPS_REPO: "demo-dev-npm"

          # [Mandatory] if JF_USER and JF_PASSWORD are not provided]
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          JF_GIT_AGGREGATE_FIXES: "true"

          # [Optional]
          # Template for the pull request title generated by Frogbot when creating pull requests with fixes.
          JF_PULL_REQUEST_TITLE_TEMPLATE: "[üê∏ Frogbot-Automatic PR] Upgrade ${IMPACTED_PACKAGE} to ${FIX_VERSION}"

          # [Mandatory]
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # [Mandatory]
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
